# Retail Sales Analytics Database

## Overview
A SQL-based retail analytics project built in PostgreSQL to analyze customer purchases, product performance, category revenue, and sales trends.

## Database Schema
- Customers
- Products
- Orders
- OrderDetails

## Skills Demonstrated
- SQL Joins
- Aggregations (SUM, COUNT)
- GROUP BY
- ORDER BY
- Revenue Analysis
- Customer Analytics
- Product Performance Reporting
- Time-Based Sales Analysis

## Key Analyses

### Customer Spending Analysis
Identified top-spending customers using multi-table joins.

### Product Performance
Measured units sold and revenue generated by each product.

### Category Revenue Analysis
Compared revenue generated across product categories.

### Monthly Sales Trends
Analyzed revenue performance by month to identify trends.

## Technologies
- PostgreSQL
- pgAdmin 4
- SQL

## Business Insights
- Laptops generated the highest revenue.
- Keyboards sold the highest number of units.
- Electronics produced the majority of revenue.
- March was the strongest sales month.